# Production environment values
global:
  imagePullPolicy: IfNotPresent

vote-api:
  replicaCount: 3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

result-api:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

worker:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

vote-ui:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

redis:
  architecture: replication # Use a primary-replica setup for HA
  auth:
    enabled: true
    password: "a-very-secure-password-from-secret" # This should be managed via secrets

postgresql:
  primary:
    persistence:
      size: 10Gi
  auth:
    postgresPassword: "another-very-secure-password-from-secret" # This should be managed via secrets
