apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-api
spec:
  replicas: { { .values.replicaCount } }
  selector:
    matchLabels:
      app: vote-api
  template:
    metadata:
      labels:
        app: vote-api
    spec:
      containers:
        - name: vote-api
          image: { { .Values.images.voteapi } }
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
