apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-api
spec:
  replicas: { { .Values.replicaCount } }
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: result-api
  template:
    metadata:
      labels:
        app: result-api
    spec:
      containers:
        - name: result-api
          image: "{{ .Values.images.resultApi }}"
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: { { .Values.postgres.user | quote } }
            - name: DB_PASSWORD
              value: { { .Values.postgres.password | quote } }
            - name: DB_NAME
              value: { { .Values.postgres.db | quote } }
            - name: ADMIN_KEY
              value: { { .Values.resultApi.adminKey | quote } }
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
