name: CD - Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true

jobs:
  deploy-prod:
    name: Deploy to Prod Environment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://your-prod-url.com # Replace with your actual prod URL
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WIF_POOL }}/providers/${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }}

      - name: Deploy to Prod
        run: |
          helm upgrade --install voting-app ./charts/voting-app \
            --namespace prod \
            --create-namespace \
            --set global.imageRegistry=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/voting-app-images \
            --set vote-api.image.tag=${{ github.event.inputs.image_tag }} \
            --set result-api.image.tag=${{ github.event.inputs.image_tag }} \
            --set worker.image.tag=${{ github.event.inputs.image_tag }} \
            --set vote-ui.image.tag=${{ github.event.inputs.image_tag }} \
            -f ./charts/voting-app/values-prod.yaml
